const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin

  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",

  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",

  FETCH_ALL_CUSTOMERS_SUCCESS: "FETCH_ALL_CUSTOMERS_SUCCESS",
  FETCH_ALL_CUSTOMERS_FAILED: "FETCH_ALL_CUSTOMERS_FAILED",

  FETCH_ALL_TECHNOLOGY_START: "FETCH_ALL_TECHNOLOGY_START",
  FETCH_ALL_TECHNOLOGY_SUCCESS: "FETCH_ALL_TECHNOLOGY_SUCCESS",
  FETCH_ALL_TECHNOLOGY_FAILED: "FETCH_ALL_TECHNOLOGY_FAILED",
  EDIT_TECHNOLOGY_SUCCESS: "EDIT_TECHNOLOGY_SUCCESS",
  EDIT_TECHNOLOGY_FAILED: "EDIT_TECHNOLOGY_FAILED",

  DELETE_TECHNOLOGY_SUCCESS: "DELETE_TECHNOLOGY_SUCCESS",
  DELETE_TECHNOLOGY_FAILED: "DELETE_TECHNOLOGY_FAILED",

  FETCH_ALL_POSTS_SUCCESS: "FETCH_ALL_POSTS_SUCCESS",
  FETCH_ALL_POSTS_FAILED: "FETCH_ALL_POSTS_FAILED",

  EDIT_POSTS_SUCCESS: "EDIT_POSTS_SUCCESS",
  EDIT_POSTS_FAILED: "EDIT_POSTS_FAILED",

  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_FAILED: "DELETE_POSTS_FAILED",

  FETCH_ALL_PROJECT_SUCCESS: "FETCH_ALL_PROJECT_SUCCESS",
  FETCH_ALL_PROJECT_FAILED: "FETCH_ALL_PROJECT_FAILED",

  EDIT_PROJECT_SUCCESS: "EDIT_PROJECT_SUCCESS",
  EDIT_PROJECT_FAILED: "EDIT_PROJECT_FAILED",

  DELETE_PROJECT_SUCCESS: "DELETE_PROJECT_SUCCESS",
  DELETE_PROJECT_FAILED: "DELETE_PROJECT_FAILED",

  FETCH_ALL_PRODUCT_SUCCESS: "FETCH_ALL_PRODUCT_SUCCESS",
  FETCH_ALL_PRODUCT_FAILED: "FETCH_ALL_PRODUCT_FAILED",

  EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_FAILED: "EDIT_PRODUCT_FAILED",

  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",
});

export default actionTypes;
